site_name: Redbrick Docs
site_url: https://docs.redbrick.dcu.ie/
repo_url: https://github.com/redbrick/docs
repo_name: redbrick/docs
use_directory_urls: true

theme:
  name: material
  logo: res/logo.png
  favicon: res/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - awesome-pages
  - callouts
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - attr_list
  - abbr
  - nl2br
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  github_org: https://github.com/redbrick

extra_css:
  - stylesheets/extra.css
