site_name: Redbrick Docs
site_url: https://docs.redbrick.dcu.ie/
repo_url: https://github.com/redbrick/docs
repo_name: redbrick/docs
use_directory_urls: true

theme:
  name: material
  logo: res/logo.png
  favicon: res/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: custom
        accent: custom

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        primary: custom
        accent: custom

plugins:
  - awesome-pages
  - callouts
  - glightbox
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - attr_list
  - abbr
  - nl2br
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

copyright:  <img class="logo" src="res/logo.png" width="20px"> <a href="https://docs.redbrick.dcu.ie">Redbrick Docs</a>

extra:
  github_org: https://github.com/redbrick
  social:
    - icon: fontawesome/solid/globe
      link: https://redbrick.dcu.ie
      name: Redbrick Website
    - icon: fontawesome/brands/github
      link: https://github.redbrick.dcu.ie
      name: Github
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.redbrick.dcu.ie
      name: Twitter
    - icon: fontawesome/brands/instagram
      link: https://instagram.redbrick.dcu.ie
      name: Instagram
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.redbrick.dcu.ie
      name: LinkedIn
    - icon: fontawesome/brands/discord
      link: https://discord.redbrick.dcu.ie
      name: Discord

extra_css:
  - stylesheets/extra.css
